import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireAdmin, requireSuperAdmin } from "@/lib/guards";
export const runtime = "nodejs";
const schema = z.object({ id: z.string().cuid().optional(), name: z.string().trim().min(3).max(100), slug: z.string().trim().min(3).max(100).regex(/^[a-z0-9-]+$/), address: z.string().trim().min(8).max(500), phone: z.string().max(30).optional().or(z.literal("")), email: z.string().email().optional().or(z.literal("")), description: z.string().max(4000).optional().or(z.literal("")), mapEmbedUrl: z.string().url().refine(v => v.startsWith("https://www.google.com/maps/embed"), "Gunakan URL Google Maps Embed").optional().or(z.literal("")), isHeadOffice: z.boolean().default(false), isActive: z.boolean().default(true), sortOrder: z.number().int().min(0).max(999).default(0) });
export async function GET() { await requireAdmin(); return NextResponse.json(await db.unit.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] })); }
export async function POST(request: Request) { try { await requireAdmin(); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 422 }); const { id, ...data } = parsed.data; const normalized = { ...data, phone: data.phone || null, email: data.email || null, description: data.description || null, mapEmbedUrl: data.mapEmbedUrl || null }; const unit = id ? await db.unit.update({ where: { id }, data: normalized }) : await db.unit.create({ data: normalized }); return NextResponse.json(unit, { status: id ? 200 : 201 }); } catch { return NextResponse.json({ error: "Tidak diizinkan atau permintaan tidak valid." }, { status: 401 }); } }
export async function DELETE(request: Request) { try { await requireSuperAdmin(); const id = z.string().cuid().parse(new URL(request.url).searchParams.get("id")); await db.unit.delete({ where: { id } }); return new NextResponse(null, { status: 204 }); } catch { return NextResponse.json({ error: "Tidak diizinkan." }, { status: 403 }); } }
